export const FETCH_ALL_LOCATIONS = 'FETCH_ALL_LOCATIONS';
export const FETCH_ALL_LOCATIONS_SUCCESS = 'FETCH_ALL_LOCATIONS_SUCCESS';
export const FETCH_ALL_LOCATIONS_FAILURE = 'FETCH_ALL_LOCATIONS_FAILURE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST_IN_PROGRESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
