export const FETCH_ALL_LOCATIONS = 'FETCH_ALL_LOCATIONS';
export const FETCH_ALL_LOCATIONS_SUCCESS = 'FETCH_ALL_LOCATIONS_SUCCESS';
export const FETCH_ALL_LOCATIONS_FAILURE = 'FETCH_ALL_LOCATIONS_FAILURE';
