export const FETCH_ALL_LOCATIONS = 'FETCH_ALL_LOCATIONS';
export const FETCH_ALL_LOCATIONS_SUCCESS = 'FETCH_ALL_LOCATIONS_SUCCESS';
export const FETCH_ALL_LOCATIONS_FAILURE = 'FETCH_ALL_LOCATIONS_FAILURE';

export const CREATE_LOCATION_REQUEST = 'CREATE_LOCATION_REQUEST_IN_PROGRESS';
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_REQUEST_SUCCESS';
export const CREATE_LOCATION_FAILURE = 'CREATE_LOCATION_REQUEST_FAILURE';

export const UPDATE_LOCATION_REQUEST = 'UPDATE_LOCATION_REQUEST_IN_PROGRESS';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_REQUEST_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_REQUEST_FAILURE';

export const DELETE_LOCATION_REQUEST = 'DELETE_LOCATION_REQUEST_IN_PROGRESS';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_REQUEST_SUCCESS';
export const DELETE_LOCATION_FAILURE = 'DELETE_LOCATION_REQUEST_FAILURE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST_IN_PROGRESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
